blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path

from website.views import (IndexView, PostDetailView, CategoryListView, TagListView, CategoryPostView, TagPostView,)

app_name = 'website'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('tags/', TagListView.as_view(), name='tag_list'),
    path('category/<str:category_slug>/', CategoryPostView.as_view(), name='category_post'),
    path('tag/<str:tag_slug>/', TagPostView.as_view(), name='tag_post'),
]

website/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    tags = models.ManyToManyField(Tag, blank=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    description = models.TextField(blank=True)
    image = models.ImageField(
        upload_to='post_images/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)
    is_public = models.BooleanField(default=False)


    class Meta:
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if self.is_public and not self.published_at:
            self.published_at = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class ContentImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.PROTECT)
    content_image = models.ImageField(upload_to='post_content_images/')

website/views.py
from django.shortcuts import render, get_object_or_404

from django.db.models import Count, Q
from django.http import Http404
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .models import Post, Category, Tag


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not obj.is_public and not self.request.user.is_authenticated:
            raise Http404
        return obj


class IndexView(ListView):
    model = Post
    template_name = 'website/index.html'


class CategoryListView(ListView):
    queryset = Category.objects.annotate(
        num_posts=Count('post', filter=Q(post__is_public=True)))


class TagListView(ListView):
    queryset = Tag.objects.annotate(num_posts=Count(
        'post', filter=Q(post__is_public=True)))

class CategoryPostView(ListView):
    model = Post
    template_name = 'website/category_post.html'

    def get_queryset(self):
        category_slug = self.kwargs['category_slug']
        self.category = get_object_or_404(Category, slug=category_slug)
        qs = super().get_queryset().filter(category=self.category)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context

class TagPostView(ListView):
    model = Post
    template_name = 'website/tag_post.html'

    def get_queryset(self):
        tag_slug = self.kwargs['tag_slug']
        self.tag = get_object_or_404(Tag, slug=tag_slug)
        qs = super().get_queryset().filter(tags=self.tag)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.tag
        return context

website/templates/website/base.html
<!-- cd ~/Desktop/python_lesson -->

{% load static %}


<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Hello, world!{% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'website/css/style.css' %}">
  </head>

  <body>

    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

website/templates/website/category_list.html
{% extends 'website/base.html' %}
{% load static %}

{% block content %}


<div class="container">
  <div class="wrapper">

    {% include "website/snippets/nav.html" %}
    <div class="home">

      <h1>カテゴリ一覧</h1>
      <ul>
        {% for category in object_list %}
        <li><a href="{% url 'website:category_post' category.slug %}">{{ category.name }} ({{ category.num_posts }})</a></li>  {% empty %}
        <li>カテゴリはありません。</li>
        {% endfor %}
      </ul>

    </div>
  </div>

</div>


{% endblock %}

website/templates/website/category_post.html
{% extends 'website/base.html' %}
{% load static %}

{% block content %}

<div class="container">
  <div class="wrapper">

  {% include "website/snippets/nav.html" %}
  <div class="home">


<h1>「{{ category.name }}」の投稿一覧</h1>
<ul>
  {% for post in object_list %}
  {% if user.is_authenticated or post.is_public %}
  <li>{% if not post.is_public %}[下書き] {% endif %}<a href="{% url 'website:post_detail' post.id %}">{{ post.title }}</a></li>
  {% else %}
  <li>投稿はありません。</li>
  {% endif %}
  {% empty %}
  <li>まだ投稿はありません。</li>
  {% endfor %}
</ul>

</div>
</div>
</div>


{% endblock %}

website/templates/website/index.html
{% extends 'website/base.html' %}
{% load static %}


{% block content %}

<div class="container">
  <div class="wrapper">
    <img class='map' src="{% static 'website/img/map.jpg' %}" alt="" >
    {% include "website/snippets/nav.html" %}
    <div class="home">
      <div class="main-images">
        <div class="parent1 parent">
          <img class='main-image main1' src="{% static 'website/img/img1.jpg' %}" alt="" >
          <div class="name1">U.S.A PHOTO GALLERY</div>
        </div>
        <div class="parent2 parent">
          <img class='main-image main2' src="{% static 'website/img/img2.jpg' %}" alt="" >
          <div class="name2">THE ULTIMATE TRAVEL PACKING LIST</div>
        </div>
        <div class="parent3 parent">
          <img class='main-image main3' src="{% static 'website/img/img3.jpg' %}" alt="" >
          <div class="name3">HOSTEL</div>
        </div>
        <div class="parent4 parent">
          <img class='main-image main4' src="{% static 'website/img/img4.jpg' %}" alt="" >
          <div class="name4">SNS</div>
        </div>
      </div>


      <h1 class="mb-4 mb-title">-- BLOG --</h1>
      <div class="row">
        <main class="col-md-8 grid">
          {% include "website/snippets/main_post_list.html" %}
        </main>
        <aside class="col-md-4">
          {% include "website/snippets/sidebar.html" %}
        </aside>
      </div>
    </div>
    <footer>
        <p>© All rights reserved by yusuke</p>
    </footer>
  </div>
</div>

{% endblock %}

website/templates/website/post_detail.html
{% extends 'website/base.html' %}
{% load static %}

{% block content %}

<div class="container">
  <div class="wrapper">
    <img class='map' src="{% static 'website/img/map.jpg' %}" alt="" >

{% include "website/snippets/nav.html" %}
<div class="home">


<h1 class='object_title'>{{ object.title }}</h1>
<p>{{ object.published_at|date }}</p>
<p>{{ object.category.name }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{% for tag in object.tags.all %}{{ tag.name }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{% endfor %}</p>





<hr>



<div class="row">
  <main class="col-md-8">
    {% if post.image %}
    <a href="{% url 'website:post_detail' post.id %}">
      <img src="{{ post.image.url }}" alt="{{ post.title }}" width="700" height="450">
    </a>
    {% endif %}
    <div class="content">
    {{ object.content|safe }}
    </div>
  </main>
<aside class="col-md-4">
  {% include "website/snippets/sidebar.html" %}
</aside>
</div>

</div>
</div>
</div>
{% endblock %}

website/templates/website/snippets/main_post_list.html
{% load static %}


{% for post in object_list %}
{% if user.is_authenticated or post.is_public %}

<div class="card mb-3">
  {% if post.image %}
  <a href="{% url 'website:post_detail' post.id %}">
    <img class="card-img-top" src="{{ post.image.url }}" alt="{{ post.title }}">
  </a>
  {% endif %}
  <div class="card-body">
    {% if not post.is_public %}
    <h5><span class="badge badge-secondary">下書き</span></h5>
    {% endif %}
    <p class="card-text">{{ post.published_at|date }}</p>
    <a href="{% url 'website:post_detail' post.id %}">
      <h5 class="card-title">{{ post.title }}</h5>
    </a>
  </div>
</div>

{% endif %}
{% endfor %}

website/templates/website/snippets/nav.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <a class="navbar-brand" href="/">旅Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About me</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Blog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Photos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Contact</a>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

website/templates/website/snippets/sidebar.html
{% load static %}


<div class="card mb-3">
  <div class="card-header">
    カテゴリ
  </div>
  <ul class="list-group list-group-flush">
    {% for category in categories|dictsort:"id" %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <a href="{% url 'website:category_post' category.slug %}" class="card-link">{{ category.name }}</a>
      <span class="badge badge-primary badge-pill">{{ category.num_posts }}</span>
    </li>
    {% endfor %}
  </ul>
</div>

<div class="card">
  <div class="card-header">
    タグ
  </div>
  <ul class="list-group list-group-flush">
    {% for tag in tags|dictsortreversed:"num_posts"|slice:":5" %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <a href="{% url 'website:tag_post' tag.slug %}" class="card-link">{{ tag.name }}</a>
      <span class="badge badge-primary badge-pill">{{ tag.num_posts }}</span>
    </li>
    {% endfor %}
  </ul>
  <div class="card-body text-center">
    <a href="{% url 'website:tag_list' %}" class="card-link">すべてのタグを見る</a>
  </div>
</div>

website/templates/website/tag_list.html
{% extends 'website/base.html' %}
{% load static %}

{% block content %}


<div class="container">
  <div class="wrapper">

{% include "website/snippets/nav.html" %}
<div class="home">

<h1>タグ一覧</h1>
<ul>
  {% for tag in object_list %}
  <li><a href="{% url 'website:tag_post' tag.slug %}">{{ tag.name }} ({{ tag.num_posts }})</a></li>  {% empty %}
  <li>タグはありません。</li>
  {% endfor %}
</ul>

</div>
</div>
</div>

{% endblock %}

website/templates/website/tag_post.html
{% extends 'website/base.html' %}
{% load static %}

{% block content %}



<div class="container">
  <div class="wrapper">

{% include "website/snippets/nav.html" %}
<div class="home">

<h1>「#{{ tag.name }}」の投稿一覧</h1>
<ul>
  {% for post in object_list %}
  {% if user.is_authenticated or post.is_public %}
  <li>{% if not post.is_public %}[下書き] {% endif %}<a href="{% url 'website:post_detail' post.id %}">{{ post.title }}</a></li>
  {% else %}
  <li>投稿はありません。</li>
  {% endif %}
  {% empty %}
  <li>まだ投稿はありません。</li>
  {% endfor %}
</ul>

</div>
</div>
</div>

{% endblock %}